"""empty message

Revision ID: 7a8db024e6aa
Revises: a5cffa318ac2
Create Date: 2026-03-24 19:27:26.684786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a8db024e6aa'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_personaje', sa.Integer(), nullable=False),
    sa.Column('id_nave', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'id_personaje', 'id_nave')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_personaje', sa.Integer(), nullable=False),
    sa.Column('id_nave', sa.Integer(), nullable=False),
    sa.Column('id_location', sa.Integer(), nullable=False),
    sa.Column('id_arma', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'id_personaje', 'id_nave', 'id_location', 'id_arma')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planet', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('id_personaje', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'dimension', 'id_personaje')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.drop_constraint('user_email_key', type_='unique')
        batch_op.drop_column('is_active')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('user_email_key', ['email'])
        batch_op.drop_column('name')

    op.drop_table('nave')
    op.drop_table('location')
    op.drop_table('favorite')
    op.drop_table('arma')
    # ### end Alembic commands ###
